
---
# handlers/main.yml

# - name: Redémarrer httpd (Rocky)
#   service:
#     name: httpd
#     state: restarted
#     enabled: yes
#   when: ansible_facts['distribution'] | lower is search("rocky")
#   become: true

- name: Redémarrer httpd (Rocky)
  ansible.builtin.shell: |
    /usr/sbin/httpd -DFOREGROUND &
  become: true
  when: ansible_os_family == "RedHat"
  changed_when: false

- name: Redémarrer apache2 (Ubuntu)
  service:
    name: apache2
    state: restarted
    enabled: yes
  when: ansible_facts['os_family'] == "Debian"
  become: true